export const SET_SURVEY_TITLE = "SET_SURVEY_TITLE";
export const SET_TEMP_QUESTION_TYPE = "SET_TEMP_QUESTION_TYPE";
export const SET_TEMP_QUESTION_TITLE = "SET_TEMP_QUESTION_TITLE";
export const PUSH_TEMP_QUESTION_CHOICE = "PUSH_TEMP_QUESTION_CHOICE";
export const PUSH_TEMP_QUESTION_TO_SURVEY = "PUSH_TEMP_QUESTION_TO_SURVEY";

export const RESET_SURVEY_STATE = "RESET_SURVEY_STATE";

export const UPLOAD_SURVEY = "UPLOAD_SURVEY";
export const DELETE_SURVEY_DATABASE = "DELETE_SURVEY_DATABASE";
export const SET_ALL_USER_SURVEYS = "SET_ALL_USER_SURVEYS";
